### ISSUE TITLE
typo on README.md

### ISSUE THREAD

**Issue by Grip** [rly0nheart/phone-number-info#1]
Hi Richard,
just to spot a little typo on step 1. of the installation:

- git clone https://github.com/rly**o**nheart/phone-number-info instead of https://github.com/rly**0**nheart/phone-number-info

Stay strong! 

F

**Comment by rly0nheart** [comment]
Hey @Grip, thanks mate! This was my most recent push since 2021😅, there might be other things I forgot to correct
